### ISSUE TITLE
[feat] 경기도 데이터 넣기

### ISSUE THREAD

**Issue by jhbaik1501** [Team-odongdong/odongdong#89]
**Description(작업 내용)**
다른 지역 데이터 모두 넣기

**Checklist**

- [x] 모든 데이터를 편하게 넣을 수 있도록, 다형성에 맞게 설계

**ETC**

**Comment by msdio** [comment]
우선순위
1. 경기도
2. 부산
3. 그 외

데이터들을 실제로 프론트에 보내는 건 알고리즘 대회 이후에 해주시면 감사합니다 ^^
